package:
  name:  psfgen
  version: {{ environ.get('BUILD_VERSION', "0.0.1" ) }}


build:
  number: {{ environ.get('BUILD_NUMBER', 0 ) }}
  script_env:
   - FC
   - CC
   - CXX
   - TRAVIS_OS_NAME


source:
  path: ../../src

 
requirements:
  build:
    - python >=2.7
  run:
    - python >=2.7
   
about:
  license: "University of Illinois NAMD Molecular Dynamics Software Non-Exclusive, Non-Commercial Use License"
  license_file: PSFGEN_LICENCE.txt
